"""
Round 2 - MCQ Quiz Bank: 10 cases x 5 stations x 3 questions.

All 10 cases are populated below (Case 01..10). To refresh the bank, run:

    python -m round1.seed_r2_mcq  # wipes Round 2 content and seeds the bank
    python -m round1.seed_r2_mcq --no-wipe   # add cases 5..10 later (keeps progress)

Structure (letter = correct option; converted to index 0-3 at seed time):

    CASES = [
        {
            "title": "...",
            "company": "",
            "case_brief": "...",   # incident narrative shown to participants
            "objective": "...",
            "stations": {
                "S1": {"name": "...", "domain": "IDENTIFY", "mcqs": [
                    {"q": "...", "options": ["A", "B", "C", "D"], "answer": "B"},
                ]},
                "S2": ...,  # COLLECT
                "S3": ...,  # ANALYZE
                "S4": ...,  # PRESERVE
                "S5": ...,  # REPORT
            },
        },
    ]

Seeder rules:
    * each case has exactly 5 stations (S1..S5) and 3 MCQs each (4 options each)
    * answer letters A-D (or indexes 0-3) - never sent to participants
    * q and options must be non-empty and not placeholders
"""

CASES = [
    # ------------------------------------------------------------------ CASE 01
    {
        "title": "The Witness Who Wasn't",
        "company": "",
        "case_brief": "Arjun was found dead inside his apartment with no obvious forced entry. "
                      "The key eyewitness's account unravels under CCTV, smart-lock, phone and "
                      "trace-evidence correlation.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "At the beginning of the investigation, what was the main incident investigators were trying to explain?",
                 "options": ["A data breach from Arjun's company",
                             "The death of Arjun inside his apartment with no obvious forced entry",
                             "The disappearance of Vikram after visiting the shop",
                             "Unauthorized access to Arjun's laptop"],
                 "answer": "B"},
                {"q": "Why did investigators initially treat Vikram as an important witness rather than a suspect?",
                 "options": ["He had previously worked as a forensic investigator",
                             "He had access to Arjun's smart lock",
                             "He provided a detailed account of seeing a masked person and continued cooperating",
                             "CCTV confirmed that he was at the shop"],
                 "answer": "C"},
                {"q": "Which initial clue most directly caused investigators to question Vikram's account?",
                 "options": ["Arjun's laptop contained security-related searches",
                             "Vikram knew Arjun professionally",
                             "The apartment had connected devices",
                             "Building CCTV showed a masked person leaving around 11:14 PM, while Vikram claimed to see the person at about 11:15 PM"],
                 "answer": "D"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Which combination of evidence would be most relevant for testing Vikram's claim that he was returning from the nearby shop?",
                 "options": ["Shop CCTV + mobile location data + phone activity",
                             "Arjun's laptop searches + witness sketch + media reports",
                             "Deleted chats + Arjun's professional history + physical trace",
                             "Smart-lock code + Arjun's laptop + witness description"],
                 "answer": "A"},
                {"q": "Investigators need to determine who may have entered Arjun's apartment during the critical period. Which evidence should they examine most directly?",
                 "options": ["Media reports about the 'key eyewitness'",
                             "Smart-lock records showing use of the temporary guest code",
                             "Vikram's description of the masked person's scar",
                             "Arjun's searches about anonymous reporting"],
                 "answer": "B"},
                {"q": "Which evidence should investigators collect to investigate why Arjun and Vikram were in conflict?",
                 "options": ["Building CCTV and shop CCTV",
                             "Smart-lock records and airplane-mode information",
                             "Deleted communications and Arjun's laptop search history",
                             "Witness sketch and clothing description"],
                 "answer": "C"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which combination most strongly undermines Vikram's claim that he was simply returning from the shop?",
                 "options": ["His detailed description of the masked person and his cooperation",
                             "Shop CCTV failing to place him there + his phone showing a location-faking application + the 22-minute airplane-mode period",
                             "Arjun's laptop searches + the existence of the smart lock",
                             "His professional relationship with Arjun + the media calling him a witness"],
                 "answer": "B"},
                {"q": "What does the smart-lock evidence establish, when considered with the rest of the case?",
                 "options": ["The guest code alone proves Vikram committed the murder",
                             "The apartment was forcibly entered by an unknown person",
                             "A temporary guest code associated with a device linked to Vikram was used at approximately 11:05 PM, establishing relevant access that must be correlated with other evidence",
                             "Vikram definitely entered the apartment at 11:15 PM"],
                 "answer": "C"},
                {"q": "Which evidence correlation most directly supports the conclusion that the alleged masked stranger may have been a fabricated lead?",
                 "options": ["Vikram's cooperation + media coverage + his detailed statement",
                             "Shop CCTV + Arjun's laptop searches + professional relationship",
                             "Building CCTV + clothing/movement comparison + timeline + absence of independent evidence for a separate masked offender",
                             "Smart-lock records + deleted messages only"],
                 "answer": "C"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which evidence should be preserved first to maintain the integrity of the investigation?",
                 "options": ["Social media profile",
                             "Smart-lock access logs",
                             "Personal photographs",
                             "Unrelated emails"],
                 "answer": "B"},
                {"q": "Why is maintaining the original state of digital evidence important?",
                 "options": ["To make the evidence easier to edit",
                             "To prevent accidental alteration of evidence",
                             "To delete irrelevant files",
                             "To speed up the investigation"],
                 "answer": "B"},
                {"q": "Which combination provides the strongest preserved evidence timeline?",
                 "options": ["CCTV footage + smart-lock logs + device activity",
                             "Social media posts only",
                             "Witness opinion only",
                             "Phone wallpaper + photographs"],
                 "answer": "A"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which sequence best represents the critical forensic timeline?",
                 "options": ["11:15 PM sighting -> 11:05 PM smart-lock entry -> 11:14 PM CCTV -> investigation",
                             "11:05 PM smart-lock entry -> 11:05-11:14 PM critical period -> 11:14 PM CCTV departure -> 11:15 PM claimed sighting",
                             "11:14 PM CCTV -> 11:05 PM smart-lock entry -> 11:15 PM shop visit -> next morning",
                             "11:05 PM shop visit -> 11:15 PM smart-lock entry -> 11:14 PM CCTV -> phone analysis"],
                 "answer": "B"},
                {"q": "Which statement is best supported by the complete evidence correlation?",
                 "options": ["The existence of a separate masked offender was independently confirmed",
                             "Vikram's shop location was confirmed by both CCTV and reliable phone data",
                             "Vikram's statement contained multiple contradictions, while digital and physical evidence connected him to the critical investigation period",
                             "The smart-lock guest code alone proves exactly what happened inside the apartment"],
                 "answer": "C"},
                {"q": "What was the key forensic breakthrough in the final reconstruction?",
                 "options": ["Vikram's detailed description of the masked stranger",
                             "The media identifying Vikram as the key eyewitness",
                             "The combination of CCTV, smart-lock logs, phone timeline, deleted communications, and physical evidence contradicting Vikram's story",
                             "The existence of a location-faking application alone"],
                 "answer": "C"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 02
    {
        "title": "The Prime Minister's Final Frame",
        "company": "",
        "case_brief": "A shooting attempt during a Prime Minister appearance. Three camera operators "
                      "were present in the media area, and a separate airport lead surfaces using a "
                      "false identity.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "At the beginning of the investigation, what can investigators establish with certainty from the event CCTV and access information?",
                 "options": ["Vikram Shah was the shooter",
                             "One of the three camera operators was responsible, but the identity is already known",
                             "All three camera operators were present in the relevant media area",
                             "The airport passenger was present at the shooting"],
                 "answer": "C"},
                {"q": "Which feature of the event makes identification of the attacker particularly difficult?",
                 "options": ["The Prime Minister's event access records were completely missing",
                             "The three camera operators had similar clothing and equipment, while faces and the shooting action were not clearly visible",
                             "Only one CCTV camera was operating at the venue",
                             "The camera operators had no registered equipment"],
                 "answer": "B"},
                {"q": "Which development creates a second investigative lead that is initially separate from the shooting investigation?",
                 "options": ["Discovery that all three camera operators had event accreditation",
                             "Discovery that the camera equipment had registration numbers",
                             "Discovery of a passenger using the identity Ravi Menon who later escapes from the airport medical area",
                             "Discovery that the Prime Minister had started his speech at approximately 4:18 PM"],
                 "answer": "C"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Investigators need to determine whether the three camera operators had legitimate access to the restricted media area. Which evidence should they examine?",
                 "options": ["Event access logs",
                             "Airport medical records",
                             "Passport records of Ravi Menon",
                             "Black Meridian Network information"],
                 "answer": "A"},
                {"q": "Investigators want to determine whether the airport passenger using the name Ravi Menon is actually connected to one of the three camera operators. Which combination of evidence is most directly relevant?",
                 "options": ["Event CCTV and camera uniforms only",
                             "Passport verification and biometric comparison",
                             "Equipment registration and event accreditation only",
                             "Prime Minister's speech timing and venue lockdown records"],
                 "answer": "B"},
                {"q": "Investigators want to reconstruct the suspect's movements before and after the event. Which collection of evidence is specifically identified in the case as useful for this purpose?",
                 "options": ["CCTV, access logs, transportation records and device timestamps",
                             "Uniform records, speech notes and employee photographs",
                             "Passport photographs, medical symptoms and event uniforms",
                             "Camera equipment prices, accreditation dates and venue layout"],
                 "answer": "A"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "What does the event CCTV establish about Arjun Rao, Daniel Thomas and Vikram Shah?",
                 "options": ["It conclusively identifies Vikram as the shooter",
                             "It establishes that all three were near the relevant area but does not by itself identify the attacker",
                             "It proves Arjun and Daniel were working together",
                             "It proves the airport passenger was not one of the camera operators"],
                 "answer": "B"},
                {"q": "Which combination provides the strongest connection between the airport passenger and Vikram Shah?",
                 "options": ["Airport CCTV + medical-area CCTV only",
                             "Passport verification + travel history only",
                             "Biometric comparison + identity records + CCTV + travel timeline",
                             "Event accreditation + camera registration only"],
                 "answer": "C"},
                {"q": "Investigators want to determine whether the airport incident and the event investigation involve the same person. Which sequence best reflects the evidence correlation described in the case?",
                 "options": ["Airport escape -> event CCTV -> motive -> passport registration",
                             "False identity -> biometric comparison -> connection to Vikram -> event and travel evidence correlation",
                             "Motive -> arrest -> airport CCTV -> equipment registration",
                             "Event CCTV -> immediate identification of Vikram -> passport verification -> motive"],
                 "answer": "B"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which evidence should investigators preserve because it can later be used to reconstruct the movements of the suspects across the two locations?",
                 "options": ["Event CCTV, airport CCTV and transportation records",
                             "Only the final investigation conclusion",
                             "Only the suspect's stated explanation",
                             "Only the event accreditation documents"],
                 "answer": "A"},
                {"q": "Investigators have recovered a physical trace associated with the crime scene and material associated with a suspect's equipment and clothing. Why is preserving this evidence important?",
                 "options": ["It provides an additional physical comparison that can support the investigative conclusion",
                             "It automatically proves motive",
                             "It replaces the need for CCTV analysis",
                             "It proves that all three camera operators were involved"],
                 "answer": "A"},
                {"q": "Which evidence set should be retained together to support the identity reconstruction shown in the case?",
                 "options": ["Real identity records, camera-crew identity records and the false Ravi Menon identity records",
                             "Only Ravi Menon's passport",
                             "Only Vikram's employee information",
                             "Only the airport medical-area CCTV"],
                 "answer": "A"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which sequence most accurately represents the final forensic reconstruction?",
                 "options": ["Airport escape -> event access -> three suspects identified -> motive established -> CCTV proves Vikram",
                             "Vikram joins the camera crew -> shooting occurs -> he travels toward the airport -> false identity is discovered -> biometric and forensic evidence connect him to the investigation",
                             "Motive discovered -> Vikram identified -> airport incident occurs -> event access is established",
                             "Event CCTV identifies Vikram -> airport identity is checked -> equipment is examined -> motive is established"],
                 "answer": "B"},
                {"q": "Which statement is best supported by the complete evidence chain?",
                 "options": ["The event CCTV alone proves Vikram was responsible",
                             "Vikram's possible motive is sufficient to establish responsibility",
                             "The combined CCTV, access, biometric, digital, travel, equipment and physical evidence links Vikram to the investigation",
                             "The false passport alone proves that Vikram committed the shooting"],
                 "answer": "C"},
                {"q": "Why are Arjun Rao and Daniel Thomas excluded from the final suspect conclusion according to the case file?",
                 "options": ["CCTV clearly shows that neither was present at the event",
                             "Their equipment was not registered with the media company",
                             "Their independently verified movement, access, equipment and digital records do not connect them to the combined critical evidence",
                             "They were both absent when the Prime Minister began his speech"],
                 "answer": "C"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 03
    {
        "title": "NX-7 Conspiracy: The Staged Suicide",
        "company": "",
        "case_brief": "The NX-7 prototype is stolen and William is found hanged under suspicious "
                      "circumstances. Credential access, USB copying and staging evidence point to a "
                      "single suspect.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "What evidence most strongly establishes that William's death should not be treated as a simple suicide?",
                 "options": ["A farewell note was found near William's body",
                             "William had financial documents in his apartment",
                             "Forensic findings indicate the fatal injury occurred before the hanging scene was created",
                             "William's laptop was still inside the apartment"],
                 "answer": "C"},
                {"q": "Which combination most directly establishes a possible connection between the NX-7 theft and the suspicious death?",
                 "options": ["Anna's family dispute + Daniel's financial problems",
                             "Missing NX-7 prototype + copied NX-7 data + staged hanging evidence",
                             "William entering the building + Anna leaving the building",
                             "Technical jacket fibre + partial fingerprint"],
                 "answer": "B"},
                {"q": "Which suspect had both authorized technical access to NX-7 and evidence of communication with a potential external buyer?",
                 "options": ["Anna Hart",
                             "Daniel Reed",
                             "Raj Menon",
                             "William Hart"],
                 "answer": "C"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Investigators want to determine whether the NX-7 data was actually removed from William's laptop. Which evidence should they prioritize?",
                 "options": ["Anna's building access record",
                             "USB connection evidence showing large amounts of NX-7 data were copied",
                             "Technical jacket fibre",
                             "William's message to Daniel"],
                 "answer": "B"},
                {"q": "Investigators need to examine whether Raj's credentials were connected to the digital theft. Which evidence combination is most relevant?",
                 "options": ["Raj's credentials accessing William's laptop at 9:39 PM + NX7 folder deletion at 9:41 PM",
                             "Anna entering at 9:12 PM + leaving at 9:18 PM",
                             "Daniel's financial difficulties + jacket fibre",
                             "William entering the building at 8:42 PM + CCTV gap"],
                 "answer": "A"},
                {"q": "Investigators want to determine whether the unidentified person entering the service entrance overlaps with the digital activity. Which evidence should be collected together?",
                 "options": ["Service entrance CCTV + internal network activity + laptop access timeline",
                             "Anna's visit + Daniel's financial situation",
                             "Fingerprint + jacket fibre only",
                             "William's message + company valuation"],
                 "answer": "A"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which sequence best matches the documented critical-period timeline?",
                 "options": ["Raj credentials -> unknown person enters -> USB copied -> CCTV resumes",
                             "Unknown person enters -> administrative access -> Raj credentials access laptop -> NX-7 deletion -> unknown person leaves",
                             "Anna enters -> Raj leaves home -> William enters -> NX-7 deletion",
                             "William enters -> Anna leaves -> Daniel enters -> Raj sends payment"],
                 "answer": "B"},
                {"q": "What is the strongest interpretation of the USB evidence when combined with the other digital evidence?",
                 "options": ["The USB alone proves Raj physically committed the murder",
                             "The USB was unrelated because William's laptop remained in the apartment",
                             "The USB identifier links the device to Raj, while the copying activity and Raj-credential access require correlation with other evidence",
                             "The USB proves Anna entered during the critical period"],
                 "answer": "C"},
                {"q": "Why should investigators not treat Raj's credentials alone as conclusive proof that Raj was physically present?",
                 "options": ["Raj had no authorized access to NX-7",
                             "Credentials can establish account activity but do not independently establish who physically used them",
                             "The laptop was not connected to any network",
                             "The credentials were used after the NX7 folder was deleted"],
                 "answer": "B"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Investigators need to preserve evidence showing whether the scene was staged. Which evidence is most important?",
                 "options": ["Forensic findings showing the fatal injury occurred before the hanging scene was created",
                             "Anna's family dispute",
                             "Raj's expected 75 lakh payment",
                             "William's commercial valuation of NX-7"],
                 "answer": "A"},
                {"q": "Which evidence should be preserved together to reconstruct the digital theft timeline?",
                 "options": ["Technical jacket fibre + partial fingerprint",
                             "USB connection/copy records + Raj credential access at 9:39 PM + NX7 deletion at 9:41 PM",
                             "Anna's 9:12 PM entry + Daniel's financial difficulties",
                             "William's message + NX-7 commercial value"],
                 "answer": "B"},
                {"q": "Which physical evidence requires careful preservation because it cannot independently identify the murderer?",
                 "options": ["Partial fingerprint and technical jacket fibre",
                             "NX-7 prototype and project files",
                             "Building access records and payment arrangement",
                             "Raj's credentials and deleted communication"],
                 "answer": "A"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which finding provides the strongest evidence of a possible financial motive for Raj?",
                 "options": ["Raj owned a similar jacket to Daniel",
                             "Raj had authorized access to NX-7",
                             "Communication with Aureon Technologies + proposed 75 lakh payment arrangement",
                             "Raj's credentials were used on William's laptop"],
                 "answer": "C"},
                {"q": "Which evidence chain most strongly connects the suspected technology theft to the staged death?",
                 "options": ["Anna's visit -> family dispute -> CCTV gap",
                             "Raj's NX-7 access -> external buyer communication -> USB copying -> Raj credential access -> file deletion -> staged hanging evidence",
                             "Daniel's financial problems -> jacket fibre -> William's message",
                             "William enters building -> Anna enters -> Anna leaves"],
                 "answer": "B"},
                {"q": "Based on the complete evidence chain provided in the case, what should the investigators report?",
                 "options": ["Anna is responsible because she was inside the building",
                             "Daniel is responsible because he had financial problems",
                             "Raj Menon is the primary suspect in a suspected murder, staged suicide and NX-7 theft, supported by correlated digital, financial, physical and timeline evidence",
                             "The death must be classified as suicide because William was found hanging"],
                 "answer": "C"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 04
    {
        "title": "The Locked Office Mystery",
        "company": "",
        "case_brief": "Vikram is found dead in a locked office. A missing-document trail, a torn "
                      "financial record and a CCTV resemblance place the focus on correlation before "
                      "attribution.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "Which evidence creates the clearest initial timeline inconsistency involving a suspect?",
                 "options": ["Priya knows where the office key is normally kept",
                             "Arjun had an argument with Vikram earlier that night",
                             "Rohan says he left at 10:45 PM, while CCTV records a person resembling him near the house at 11:15 PM",
                             "The office key was found inside the house"],
                 "answer": "C"},
                {"q": "Which combination most directly establishes that the investigation involves both a business issue and activity shortly before Vikram's death?",
                 "options": ["Arjun's argument + Priya's knowledge of the house",
                             "Missing-document message + confidential business file opened shortly before the incident",
                             "CCTV resemblance + office key",
                             "Locked door + lack of forced-entry damage"],
                 "answer": "B"},
                {"q": "Why should investigators avoid identifying Rohan solely from E01?",
                 "options": ["Rohan never visited Vikram's house",
                             "The CCTV was recorded after the estimated time of death",
                             "The footage shows only a person resembling Rohan, so identity is not conclusively established",
                             "Rohan had no possible motive"],
                 "answer": "C"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Which set of evidence should investigators collect to investigate the suspected timeline contradiction involving Rohan?",
                 "options": ["Only the torn document and office key",
                             "CCTV footage, Rohan's statement, and the relevant timeline",
                             "Only Arjun's statement and Priya's work history",
                             "Only the financial dispute information"],
                 "answer": "B"},
                {"q": "Which evidence combination is most useful for examining whether the missing documents were connected to activity inside the office?",
                 "options": ["Phone message + confidential computer file + torn financial document",
                             "CCTV resemblance + Priya's knowledge of the key",
                             "Arjun's argument + Rohan's financial dispute",
                             "Office door + kitchen item"],
                 "answer": "A"},
                {"q": "Which information should be collected before concluding how the locked office was accessed?",
                 "options": ["Only the fact that Priya knew the key location",
                             "Only Rohan's financial dispute",
                             "Office key evidence, office-access information, computer activity, and the timeline",
                             "Only the CCTV image of the person resembling Rohan"],
                 "answer": "C"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which sequence best represents the evidence chain described in the case?",
                 "options": ["CCTV -> Motive -> Kitchen item -> Death -> Phone",
                             "Missing documents -> Phone message -> Confidential file -> Financial document -> Access/timeline analysis",
                             "Arjun's argument -> Priya's work -> Rohan's meeting -> Locked door",
                             "Office key -> CCTV resemblance -> Motive -> Missing documents"],
                 "answer": "B"},
                {"q": "Which conclusion is supported by the available evidence regarding Rohan's 10:45 PM departure statement?",
                 "options": ["Rohan definitely returned to the house",
                             "Rohan definitely caused Vikram's death",
                             "His statement requires further verification because a person resembling him was recorded near the house at 11:15 PM",
                             "The CCTV proves that Rohan was inside the office at 11:15 PM"],
                 "answer": "C"},
                {"q": "Which evidence is most important when determining whether a suspect's possible motive is connected to the incident?",
                 "options": ["Motive alone",
                             "Motive combined with access, opportunity, digital evidence, physical evidence, and timeline",
                             "Knowledge of the office-key location alone",
                             "CCTV resemblance alone"],
                 "answer": "B"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which evidence should be preserved together to maintain the timeline of the investigation?",
                 "options": ["CCTV timestamps, phone activity, computer activity, suspect statements, and estimated time of death",
                             "Only the CCTV footage",
                             "Only the financial document",
                             "Only the office key"],
                 "answer": "A"},
                {"q": "Why should the torn business document be preserved as evidence?",
                 "options": ["Because any torn paper automatically proves responsibility",
                             "Because it may connect the missing documents, financial dispute, and activity inside the office",
                             "Because it proves Rohan was inside the office",
                             "Because it proves Priya used the office key"],
                 "answer": "B"},
                {"q": "Which statement best describes how the office-key evidence should be treated?",
                 "options": ["Finding the key inside the house proves who locked the office",
                             "The key should be considered together with access information, computer activity, and the timeline",
                             "Priya's knowledge of the key location proves she used it",
                             "The locked door proves that nobody entered the office"],
                 "answer": "B"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which conclusion can investigators directly support from the case evidence?",
                 "options": ["Rohan is conclusively identified as the person in the CCTV footage",
                             "Priya definitely entered the office because she knew where the key was",
                             "Rohan's timeline requires further investigation because his stated departure time conflicts with CCTV showing a person resembling him later",
                             "Arjun definitely caused the death because he argued with Vikram"],
                 "answer": "C"},
                {"q": "Which evidence chain provides the strongest basis for the final investigation report?",
                 "options": ["Motive -> Suspect -> Conclusion",
                             "Phone -> Computer -> Financial document -> Key/access -> CCTV -> Timeline -> Suspect statements",
                             "CCTV resemblance -> Motive -> Conclusion",
                             "Kitchen item -> Key -> Conclusion"],
                 "answer": "B"},
                {"q": "What is the most appropriate final investigative position based strictly on the supplied case?",
                 "options": ["The person responsible can be identified solely from the financial dispute",
                             "The CCTV resemblance conclusively identifies Rohan",
                             "The evidence must be correlated across access, opportunity, digital activity, documents, CCTV, and timeline before final attribution",
                             "Knowledge of the office key establishes responsibility"],
                 "answer": "C"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 05
    {
        "title": "The Last Dose",
        "company": "",
        "case_brief": "Consumers of VITA-X fall critically ill. Toxicology ties the victims to the "
                      "experimental compound VR-42, while digital records expose an unofficial "
                      "distribution and monitoring operation.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "What is the strongest common connection between the victims?",
                 "options": ["They all knew each other personally",
                             "They all worked for the same company",
                             "They consumed VITA-X containing the same experimental compound, VR-42",
                             "They all purchased VITA-X from the same medical shop"],
                 "answer": "C"},
                {"q": "Which evidence establishes that VR-42 was not an ordinary vitamin ingredient?",
                 "options": ["Medical-shop receipts",
                             "The recovered laboratory backup identifying VR-42 as an experimental compound not approved for human consumption",
                             "CCTV showing sealed VITA-X cartons",
                             "Payments made to the distributor"],
                 "answer": "B"},
                {"q": "Which evidence most strongly suggests that the distribution involved systematic monitoring of consumers?",
                 "options": ["A single VITA-X bottle recovered from a victim's home",
                             "A suspicious QR code on the packaging",
                             "A deleted spreadsheet containing Batch ID, Shop ID, units, customer feedback, reaction, and result",
                             "The existence of different VITA-X labels"],
                 "answer": "C"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Which evidence set would best establish the connection between the victims and VITA-X?",
                 "options": ["Victim toxicology reports + VITA-X tablet samples",
                             "Raj's login + Anita's quality report",
                             "CCTV + payment records only",
                             "Distributor records + Raj's credentials only"],
                 "answer": "A"},
                {"q": "Which evidence should investigators collect to examine the suspected unofficial supply chain?",
                 "options": ["Only the laboratory backup",
                             "Medical-shop receipts + distributor records + delivery CCTV + payment trail",
                             "Only the consumer-reaction spreadsheet",
                             "Only the internal quality report"],
                 "answer": "B"},
                {"q": "Which evidence is most important for determining whether Raj's account was actually used by Raj?",
                 "options": ["The fact that Raj worked with VR-42",
                             "The fact that the spreadsheet originated from a Jubilant Biosys research workstation",
                             "Device information and access records comparing the research workstation with the second device that used Raj's credentials",
                             "The existence of the laboratory backup"],
                 "answer": "C"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which sequence best reconstructs the central investigation chain?",
                 "options": ["Payment -> Victim -> Laboratory -> CCTV -> Packaging",
                             "VR-42 laboratory evidence -> VITA-X -> unofficial distribution -> consumers -> toxicology -> digital records",
                             "Raj's account -> Anita's report -> Vikram's payment -> Victims",
                             "CCTV -> Medical shop -> Raj -> Laboratory -> Victims"],
                 "answer": "B"},
                {"q": "What does the consumer-reaction spreadsheet most strongly indicate?",
                 "options": ["The product was being sold as a normal vitamin with no monitoring",
                             "Someone was systematically recording consumer responses to the distributed batches",
                             "Raj personally contacted every victim",
                             "The distributor legally conducted a clinical trial"],
                 "answer": "B"},
                {"q": "Why should investigators not conclude that Raj controlled the entire operation solely from E12?",
                 "options": ["Raj had no connection to VR-42",
                             "The spreadsheet was not connected to a research workstation",
                             "Raj's credentials were also used from another device, creating uncertainty about who actually controlled the account",
                             "The spreadsheet contained no consumer information"],
                 "answer": "C"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which evidence combination should be preserved to reconstruct how VITA-X reached consumers?",
                 "options": ["Packaging analysis + medical-shop receipts + distributor records + CCTV + payment records",
                             "Only the VITA-X packaging",
                             "Only victim statements",
                             "Only the laboratory backup"],
                 "answer": "A"},
                {"q": "Why is the deleted consumer-reaction spreadsheet especially important to preserve?",
                 "options": ["It proves that every victim was personally selected",
                             "It records batch, shop, supply, customer-feedback, reaction, and result information that may reveal how the operation was monitored",
                             "It proves that Raj personally distributed every tablet",
                             "It establishes the identity of the CCTV delivery person"],
                 "answer": "B"},
                {"q": "Why should Anita's deleted quality report and the related forensic access logs be preserved together?",
                 "options": ["They prove Anita deleted the report herself",
                             "They show that an abnormal VR-42 concentration was reported and that another account accessed the report afterward",
                             "They prove Vikram created the VITA-X packaging",
                             "They establish that the distributor was responsible for the deaths"],
                 "answer": "B"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which conclusion is directly supported by the combined toxicology and product evidence?",
                 "options": ["Every victim was individually targeted",
                             "VITA-X was unrelated to the victims' reactions",
                             "VITA-X containing VR-42 provides a common link between the product and multiple victims",
                             "Raj personally administered VR-42 to every victim"],
                 "answer": "C"},
                {"q": "Which evidence chain provides the strongest basis for reporting a coordinated operation?",
                 "options": ["Motive -> Raj's account -> Conclusion",
                             "VR-42 in victims -> VR-42 in VITA-X -> unofficial distribution -> consumer-reaction tracking -> digital records -> laboratory evidence",
                             "Vikram's payments -> CCTV resemblance -> Conclusion",
                             "Anita's deleted report -> Raj's credentials -> Conclusion"],
                 "answer": "B"},
                {"q": "What is the most appropriate final investigative conclusion based strictly on the case?",
                 "options": ["Raj is conclusively proven to be the sole person responsible because his credentials appear in the spreadsheet",
                             "Vikram is conclusively responsible because he handled distribution",
                             "The evidence supports an organized unauthorized distribution and monitoring operation, but individual responsibility must be established by correlating access, knowledge, device, communication, financial, and distribution evidence",
                             "Anita is responsible because the quality report disappeared after she submitted it"],
                 "answer": "C"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 06
    {
        "title": "The Altered Tender Document",
        "company": "",
        "case_brief": "A procurement account authenticates in the dead of night from an unusual "
                      "device, and the tender document is altered and copied to a USB with ties to an "
                      "IT support workstation.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "Which account was compromised during the incident?",
                 "options": ["Arun's IT support account",
                             "Karthik's documentation account",
                             "Priya's priya.procurement account",
                             "The company's archive account"],
                 "answer": "C"},
                {"q": "Which event is the clearest initial indicator that Priya's account was being misused?",
                 "options": ["Priya discovered the altered document at 9:20 AM",
                             "The account successfully authenticated at 2:13 AM from unusual device WIN-LAP-27",
                             "Karthik had legitimate access to tender documents",
                             "The original tender was moved to Archive at 8:47 AM"],
                 "answer": "B"},
                {"q": "Why should investigators NOT conclude that Priya committed the attack simply because her account was used?",
                 "options": ["Priya did not have access to the tender document",
                             "Priya's account was never successfully authenticated",
                             "The account activity occurred from an unusual device and was preceded by suspicious password-reset and email activity",
                             "Priya had no knowledge of the tender"],
                 "answer": "C"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Which evidence combination would be most useful for determining how Priya's account became compromised?",
                 "options": ["CCTV + document comparison + Karthik's access history",
                             "Password reset record + suspicious email timeline + process logs",
                             "USB record + tender pricing + physical access record",
                             "Archive record + Priya's statement + tender total"],
                 "answer": "B"},
                {"q": "Investigators want to establish that the tender files were actually copied during the suspicious session. Which evidence should they examine?",
                 "options": ["E13 USB File Record together with E11 Account Activity",
                             "E1 Server Alert together with E3 CCTV",
                             "E14 IT Access Record together with E12 Document Comparison",
                             "E15 Password Reset Record together with E2 Account Log"],
                 "answer": "A"},
                {"q": "Which evidence would be most useful for connecting Arun's workstation to the USB used during the attack?",
                 "options": ["E16 USB Device Attribution",
                             "E12 Document Comparison",
                             "E3 CCTV",
                             "E15 Password Reset Record"],
                 "answer": "A"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which sequence best represents the attack timeline?",
                 "options": ["Account login -> USB connection -> suspicious email -> PowerShell -> document modification",
                             "Password reset -> suspicious email -> attachment opened -> macro/PowerShell -> account login -> USB connection -> tender access -> modification/copying",
                             "USB connection -> password reset -> tender modification -> suspicious email -> account login",
                             "Tender modification -> account login -> suspicious email -> PowerShell -> password reset"],
                 "answer": "B"},
                {"q": "Which combination provides the strongest correlation connecting Arun to the attack?",
                 "options": ["Arun had legitimate IT access and knew the system",
                             "Arun's workstation had PowerShell activity, USB-77A91 was previously registered to his workstation, modified pricing notes were recovered from it, and physical/network activity overlapped the attack",
                             "Arun had previously performed a legitimate remote-maintenance session",
                             "Arun was an IT Support Engineer while Karthik worked with documents"],
                 "answer": "B"},
                {"q": "What do the original and modified tender documents demonstrate?",
                 "options": ["The document was accidentally edited during normal work",
                             "Only the filename was changed",
                             "Financially important information, including the bank account and tender pricing, was deliberately altered",
                             "The tender was completely deleted from the server"],
                 "answer": "C"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which group of evidence should investigators preserve to reconstruct the complete attack?",
                 "options": ["Only the modified tender document",
                             "Account logs, password-reset records, email/process logs, USB records, network records, workstation evidence, and document versions",
                             "Only Arun's workstation",
                             "Only the CCTV footage"],
                 "answer": "B"},
                {"q": "Why is preserving the original digital evidence important in this case?",
                 "options": ["It allows investigators to replace uncertain evidence with assumptions",
                             "It allows the original records to be verified and correlated without relying only on altered or summarized copies",
                             "It proves the account owner committed the crime",
                             "It eliminates the need for document comparison"],
                 "answer": "B"},
                {"q": "Which evidence should be preserved particularly carefully because it directly connects a physical device to the suspicious session?",
                 "options": ["USB-77A91 device history and attribution records",
                             "Priya's statement alone",
                             "The tender's final price alone",
                             "Karthik's job description"],
                 "answer": "A"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which conclusion is best supported by the complete evidence?",
                 "options": ["Priya committed the attack because her account was used",
                             "Karthik committed the attack because he had legitimate tender access",
                             "Arun is connected to the attack through correlated USB, network, PowerShell, recovered-file, and physical-access evidence, while Priya's account was used as cover",
                             "The attacker cannot be identified because Priya's account was compromised"],
                 "answer": "C"},
                {"q": "Which evidence chain provides the strongest basis for identifying Arun as the insider culprit?",
                 "options": ["Arun's job role -> previous IT access -> Priya's account login",
                             "USB-77A91 attribution -> Arun network correlation -> matching pricing file -> PowerShell activity -> physical access during the attack",
                             "Karthik's document access -> Priya's account -> altered tender",
                             "Suspicious email -> Priya's password reset -> altered tender"],
                 "answer": "B"},
                {"q": "What was the most likely purpose of using Priya's compromised account?",
                 "options": ["To make the tender easier for Priya to access",
                             "To hide the attacker's identity by making the activity appear to originate from Priya",
                             "To prevent the USB from being detected",
                             "To restore the original tender automatically"],
                 "answer": "B"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 07
    {
        "title": "The Server Room Murder",
        "company": "",
        "case_brief": "Arjun is found dead in the secured server room while the financial database is "
                      "breached at the same time. A badge, a token reset and a former laptop suggest "
                      "the credentials were used by someone else.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "What is the primary incident investigators are dealing with?",
                 "options": ["A database outage caused by a server failure",
                             "A homicide occurring during a suspected cyberattack",
                             "An employee access-card malfunction",
                             "A physical theft from the server room"],
                 "answer": "B"},
                {"q": "Which combination makes the incident especially suspicious?",
                 "options": ["Arjun entered at 9:00 PM and Meera arrived at 6:30 AM",
                             "Sneha had a performance dispute and Vikram was a former employee",
                             "A financial database was breached while Arjun was later found dead in the secured server room",
                             "The server room contained several company computers"],
                 "answer": "C"},
                {"q": "Which evidence initially makes Rakesh a strong person of interest?",
                 "options": ["His badge was used at 10:22 PM",
                             "His admin account was active during the database export",
                             "His laptop MAC address appeared in the Wi-Fi logs",
                             "He was seen entering the server room at 9:00 PM"],
                 "answer": "B"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Investigators want to determine whether Rakesh's credentials were used by someone physically inside the building. Which evidence combination is most relevant?",
                 "options": ["CCTV + autopsy report + shoe scuff",
                             "Token reset record + Break Room Wi-Fi information + server breach log",
                             "Sneha's performance review + Meera's patrol log",
                             "Lanyard clip + blood smear + Arjun's shoes"],
                 "answer": "B"},
                {"q": "Which evidence would best help connect the unknown server-room visitor to the cyberattack timeline?",
                 "options": ["Vikram's old laptop Wi-Fi record and the server breach log",
                             "Sneha's performance review and Arjun's laptop screen",
                             "Meera's patrol log and the suspected weapon",
                             "Rakesh's personal message and the broken lanyard clip"],
                 "answer": "A"},
                {"q": "Why should investigators collect both the digital breach evidence and the physical crime-scene evidence?",
                 "options": ["Digital evidence cannot be used in a homicide investigation",
                             "Physical evidence automatically identifies the cyber attacker",
                             "Their overlapping timeline may show whether the cyberattack and murder were connected",
                             "CCTV footage is always more reliable than server logs"],
                 "answer": "C"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which sequence correctly follows the important events in the case?",
                 "options": ["Arjun enters -> breach begins -> token reset -> unknown person enters -> session terminated -> person exits",
                             "Suspicious message -> token reset -> Arjun enters -> unknown person enters -> breach/database export -> session terminated -> person exits",
                             "Token reset -> suspicious message -> breach -> Arjun enters -> person exits -> session terminated",
                             "Arjun enters -> unknown person enters -> suspicious message -> token reset -> database export -> person exits"],
                 "answer": "B"},
                {"q": "Which combination most strongly supports the possibility that Rakesh's credentials were being used by another person?",
                 "options": ["Rakesh had administrator privileges and claimed to work from home",
                             "Rakesh received a suspicious message and his account appeared in the breach",
                             "The token was reset from Break Room Wi-Fi, while the breach later used Rakesh's credentials and Vikram's old laptop appeared inside the building",
                             "Rakesh's account performed a database export and Arjun's report was incomplete"],
                 "answer": "C"},
                {"q": "Why can investigators NOT conclusively identify the person seen entering the server room at 10:22 PM as Vikram?",
                 "options": ["Vikram had no motive",
                             "The CCTV face is not visible, and the physical evidence has not yet been matched to him",
                             "Vikram's laptop was outside the building",
                             "Vikram was never mentioned in the investigation"],
                 "answer": "B"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which action best protects the integrity of the suspected weapon evidence?",
                 "options": ["Repackage it whenever investigators need to examine it",
                             "Keep it sealed, document its handling, and maintain the chain-of-custody record",
                             "Give it directly to the investigator who found it",
                             "Remove the original evidence tag before laboratory examination"],
                 "answer": "B"},
                {"q": "Which group contains evidence that should be preserved because it can establish both the cyber and physical timeline?",
                 "options": ["Server logs, token-reset records, CCTV, door-access logs, and relevant physical evidence",
                             "Only the victim's laptop",
                             "Only the suspects' personnel records",
                             "Only the suspected weapon"],
                 "answer": "A"},
                {"q": "The forensic lab receives weapon tag #M-207 with the seal intact. What does this establish?",
                 "options": ["The weapon definitely belongs to Vikram",
                             "The weapon was definitely used by the person on CCTV",
                             "The evidence package remained sealed between documented collection and laboratory receipt",
                             "The weapon is automatically proven to be the murder weapon"],
                 "answer": "C"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Based only on the case evidence, which conclusion is the most appropriately supported?",
                 "options": ["Rakesh definitely committed both crimes because his account was used",
                             "Sneha committed the murder because she had a dispute with Arjun",
                             "The evidence strongly points toward misuse of Rakesh's credentials by someone inside the building, with Vikram being a primary person of interest, but the killer is not conclusively identified",
                             "Meera committed both crimes because she had master-key access"],
                 "answer": "C"},
                {"q": "Which evidence correlation is strongest for identifying Vikram as the primary person of interest?",
                 "options": ["His previous termination + his laptop connecting inside the building during the attack window + the breach using Rakesh's credentials",
                             "His previous termination alone",
                             "His laptop being a former company device alone",
                             "The fact that he had publicly threatened consequences alone"],
                 "answer": "A"},
                {"q": "What remains unproven at the end of the investigation?",
                 "options": ["That a database export occurred",
                             "That Arjun died in the server room",
                             "The exact identity of the person who physically struck Arjun and whether that person was definitely Vikram",
                             "That Rakesh's credentials were used during the breach"],
                 "answer": "C"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 08
    {
        "title": "The Vanishing Scholarship",
        "company": "",
        "case_brief": "Aadhira's top scholarship ranking drops to #19 while Rohan climbs to #1. The "
                      "admin account's database changes, a suspicious verification email and a "
                      "two-computer USB trail all need correlation.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "What was the primary incident investigators needed to explain?",
                 "options": ["Unauthorized access to the college Wi-Fi network",
                             "Aadhira's scholarship ranking changing from #1 to #19 while Rohan moved from #7 to #1",
                             "Vikram's USB device being connected to two computers",
                             "A suspicious email being sent from a fake scholarship address"],
                 "answer": "B"},
                {"q": "Which system was directly compromised during the incident?",
                 "options": ["The college's CCTV system",
                             "The faculty email system",
                             "The scholarship database and ranking records",
                             "The campus Wi-Fi authentication server"],
                 "answer": "C"},
                {"q": "Which suspect initially appears most suspicious because their account performed the database modifications?",
                 "options": ["Rohan Iyer",
                             "Meera Shah",
                             "Vikram Rao",
                             "Arjun Menon"],
                 "answer": "D"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Investigators want to determine who physically controlled the administrator workstation during the database modifications. Which combination of evidence is most relevant?",
                 "options": ["Administrator workstation login history, CCTV, Wi-Fi logs and door-access records",
                             "Aadhira's scholarship amount, faculty recommendation and Rohan's final rank",
                             "Only Rohan's student account log",
                             "Only Vikram's USB history"],
                 "answer": "A"},
                {"q": "Which evidence would be most important for investigating the suspicious scholarship verification email?",
                 "options": ["CCTV showing Arjun leaving campus",
                             "The email sender address and the metadata of Scholarship_Verification.pdf",
                             "Vikram's support account login",
                             "The administrator database logout record"],
                 "answer": "B"},
                {"q": "Investigators discover that USB-7F31 appears on both Vikram's workstation and the administrator computer within seconds. What should they collect to investigate this clue further?",
                 "options": ["The original USB device, both workstation histories and relevant system timestamps",
                             "Only Vikram's statement that he was fixing a network issue",
                             "Only the administrator account password",
                             "Only the final scholarship ranking"],
                 "answer": "A"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "The database audit log shows that the admin account changed Aadhira's and Rohan's scores. What can investigators conclude from this evidence alone?",
                 "options": ["Arjun personally performed the changes",
                             "The administrator account was used to perform the changes, but the account use alone does not identify the person",
                             "Rohan personally used the administrator account",
                             "Vikram definitely used the administrator account"],
                 "answer": "B"},
                {"q": "Which evidence correlation most strongly points toward Rohan's involvement in preparing the deception?",
                 "options": ["Rohan's scholarship rank increased from #7 to #1",
                             "Rohan's account logged in at 11:41 PM",
                             "The verify_2841.tmp file was created at 11:30:51 PM by username r.iyer, and the same CASE-VERIFY-2841 identifier appears in the suspicious PDF QR code",
                             "Rohan's phone was connected to campus Wi-Fi"],
                 "answer": "C"},
                {"q": "Which sequence best matches the critical timeline described in the case?",
                 "options": ["Rohan login -> suspicious email -> Arjun leaves -> database changes -> USB connection",
                             "Arjun leaves -> Rohan login -> suspicious email -> Vikram enters IT room -> database changes",
                             "Suspicious email -> Vikram enters IT room -> unknown device appears in the administrator area -> administrator database changes -> Rohan login",
                             "Vikram enters IT room -> Rohan login -> suspicious email -> administrator database changes -> Arjun leaves"],
                 "answer": "C"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which action is most appropriate when investigators acquire the administrator workstation for forensic examination?",
                 "options": ["Modify the original system to test whether the database changes can be reproduced",
                             "Create a forensic image and analyze the copy while preserving the original",
                             "Delete unrelated files before collecting the workstation",
                             "Allow the suspect to continue using the workstation before imaging it"],
                 "answer": "B"},
                {"q": "Which evidence should be preserved quickly because it may be overwritten or lost?",
                 "options": ["CCTV and access-control records covering the relevant period",
                             "Only the final scholarship ranking",
                             "Only the suspects' written statements",
                             "Only the scholarship amount awarded to Aadhira"],
                 "answer": "A"},
                {"q": "Which practice is required to maintain the integrity of the collected evidence according to the case instructions?",
                 "options": ["Allow different investigators to exchange evidence without documentation",
                             "Analyze original devices directly and avoid making copies",
                             "Record who collected, transferred and analyzed each evidence item and preserve the originals",
                             "Delete duplicate logs before beginning analysis"],
                 "answer": "C"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which conclusion is most consistent with the complete evidence chain provided in the case?",
                 "options": ["Arjun must be the culprit because the admin account performed the changes",
                             "Vikram must be the culprit because his USB appeared on two computers",
                             "Rohan is the intended primary culprit, with his involvement supported by the Rohan-associated artifact, suspicious verification process, unknown device and resulting scholarship manipulation",
                             "Meera must be the culprit because her recommendation score was changed"],
                 "answer": "C"},
                {"q": "Which piece of evidence is specifically designed as a misleading clue against Vikram?",
                 "options": ["The verify_2841.tmp file created by r.iyer",
                             "The suspicious scholarship email",
                             "USB-7F31 appearing on Vikram's workstation and the administrator computer",
                             "Rohan's scholarship status changing to SELECTED"],
                 "answer": "C"},
                {"q": "What important limitation should investigators state in their final report?",
                 "options": ["The administrator account activity alone does not prove who physically performed the database changes",
                             "Rohan's benefit alone proves he performed every action",
                             "Vikram's USB presence proves he manipulated the database",
                             "The suspicious email proves that Aadhira sent the database changes"],
                 "answer": "A"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 09
    {
        "title": "The 2:13 AM Shadow File",
        "company": "",
        "case_brief": "PROJECT PHOENIX files are copied at 2:13 AM through a login that may not have "
                      "been Devika's. A hooded figure, a USB and a malfunctioning card reader keep the "
                      "operator's identity open.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "What is the main incident investigators are trying to explain?",
                 "options": ["A physical break-in at the Cyber Security Lab",
                             "Unauthorized access to PROJECT PHOENIX followed by copying of project files",
                             "A failure of the college recovery-email system",
                             "A dispute between Devika and Priya"],
                 "answer": "B"},
                {"q": "Which event first provides strong evidence that Devika's account may have been compromised?",
                 "options": ["Devika logged out at 10:02 PM",
                             "Sanjay's card showed an exit at 9:47 PM",
                             "Devika's password was changed at 1:42 AM even though she said she did not change it",
                             "A person wearing a hood entered the laboratory"],
                 "answer": "C"},
                {"q": "Which clue most directly shows that the investigation cannot simply assume the successful login was made by Devika?",
                 "options": ["The login used the DEVIKA username",
                             "The login occurred at 2:13 AM",
                             "The login occurred on LAB-PC-04, which had been powered on before the login and had a USB keyboard connected at 2:05 AM",
                             "Devika had uploaded the project files earlier that night"],
                 "answer": "C"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Investigators want to determine whether PROJECT PHOENIX was actually copied to an external device. Which evidence is most directly relevant?",
                 "options": ["CCTV clothing and Sanjay's access-card record",
                             "USB device record and USB registry",
                             "Devika's statement and recovery email",
                             "Deleted file and corridor CCTV"],
                 "answer": "B"},
                {"q": "Which evidence combination would best establish the sequence from account compromise to unauthorized file access?",
                 "options": ["Password-change alert -> recovery-email record -> network connection log -> server login log",
                             "Sanjay's previous USB connection -> Devika's project upload -> CCTV clothing -> suspect list",
                             "Access-card record -> performance dispute -> server location -> final report",
                             "Lab-PC shutdown -> Sanjay's 9:47 PM exit -> project folder name -> CCTV corridor"],
                 "answer": "A"},
                {"q": "Investigators need to determine whether the USB device used at 2:15 AM had previously been connected to a suspect's computer. Which evidence should they compare?",
                 "options": ["E-05 USB Device Record with E-06 USB Registry",
                             "E-02 Login Information with E-07 CCTV",
                             "E-04 Password Change Alert with E-08 Access Card",
                             "E-10 Recovery Email with E-11 Deleted File"],
                 "answer": "A"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which sequence best represents when the attack activity actually began?",
                 "options": ["DEVIKA login -> USB connection -> password change -> remote session -> file transfer",
                             "LAB-PC-04 network connection -> remote session -> recovery/password activity -> access-card event -> DEVIKA login -> USB connection -> file transfer",
                             "Sanjay's 9:47 PM exit -> DEVIKA logout -> CCTV entry -> USB connection -> password change",
                             "DEVIKA logout -> DEVIKA login -> remote session -> password change -> USB connection"],
                 "answer": "B"},
                {"q": "What is the strongest correlation indicating that the attacker had access to LAB-PC-04 before the 2:13 AM login?",
                 "options": ["The computer was shut down at 2:21 AM",
                             "The CCTV face was hidden by a hood",
                             "LAB-PC-04 connected to the network at 1:50 AM, a remote session occurred at 1:51 AM, and the recovery/password activity originated from LAB-PC-04 before the 2:13 AM login",
                             "Sanjay's card was recorded at 2:03 AM"],
                 "answer": "C"},
                {"q": "Why should Sanjay's access-card record NOT be treated as conclusive proof that Sanjay personally entered the lab?",
                 "options": ["Sanjay did not have physical access to the lab",
                             "The card system had a temporary malfunction and manual authentication was enabled during the relevant period",
                             "Sanjay's card was never recorded by the system",
                             "The CCTV clearly shows another named suspect"],
                 "answer": "B"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which group of evidence should be preserved together to maintain the digital attack timeline?",
                 "options": ["Server logs, LAB-PC-04 logs, recovery/password records, network connection logs, and USB records",
                             "Only CCTV footage",
                             "Only Sanjay's access-card record",
                             "Only the deleted text file"],
                 "answer": "A"},
                {"q": "Why is it important to preserve the original evidence before relying on individual clues such as the USB record or access-card event?",
                 "options": ["So investigators can replace unclear evidence with assumptions",
                             "So the original records remain available for verification and correlation with other evidence",
                             "So only the strongest suspect's evidence is retained",
                             "So CCTV evidence becomes unnecessary"],
                 "answer": "B"},
                {"q": "Which evidence requires particular caution because the case itself identifies a reliability problem?",
                 "options": ["PROJECT PHOENIX server log",
                             "USB device record",
                             "Sanjay's 2:03 AM access-card event",
                             "Password-change alert"],
                 "answer": "C"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which conclusion is best supported by the complete evidence?",
                 "options": ["Sanjay is conclusively proven to be the attacker because his card and USB were involved",
                             "Devika stole her own files because her account was used",
                             "Devika's account was compromised and unauthorized activity occurred through LAB-PC-04, while Sanjay's USB/card links make him highly relevant but do not independently prove that he was the person operating the system",
                             "The CCTV conclusively identifies the attacker as Sanjay"],
                 "answer": "C"},
                {"q": "Which evidence chain most strongly supports the conclusion that the attack began before the 2:13 AM login?",
                 "options": ["Sanjay exited at 9:47 PM -> Devika logged out -> CCTV showed a hood",
                             "LAB-PC-04 connected at 1:50 AM -> remote session at 1:51 AM -> recovery request at 1:39 AM/1:40 AM -> password changed at 1:42 AM -> DEVIKA login at 2:13 AM",
                             "USB connected at 2:15 AM -> files copied -> computer shut down",
                             "Sanjay's card event at 2:03 AM -> Devika login -> computer shutdown"],
                 "answer": "B"},
                {"q": "What remains unproven from the supplied evidence?",
                 "options": ["That PROJECT PHOENIX files were accessed",
                             "That Devika's account was used at 2:13 AM",
                             "That USB-774A was connected at 2:15 AM",
                             "The exact identity of the person who physically operated LAB-PC-04 and carried out the entire attack"],
                 "answer": "D"},
            ]},
        },
    },
    # ------------------------------------------------------------------ CASE 10
    {
        "title": "The Signal in the Parking Lot",
        "company": "",
        "case_brief": "A rogue NEONFORGE lookalike network appears, an unknown device connects, and "
                      "privileged server access follows. Device fingerprints point away from one "
                      "suspect and toward Priya's workstation.",
        "objective": "Identify, collect, analyze, preserve and report on the full evidence chain.",
        "stations": {
            "S1": {"name": "Establish the Incident", "domain": "IDENTIFY", "mcqs": [
                {"q": "Which combination of observations most clearly establishes the primary incident that investigators need to investigate?",
                 "options": ["Rahul was seen in the parking area while Sanjay was monitoring a switch",
                             "A rogue SSID appeared, an unknown device connected to it, and a successful authentication followed",
                             "Priya left the lab and Rahul's laptop was active",
                             "The legitimate company network was operating normally while Sanjay used SWITCH-02"],
                 "answer": "B"},
                {"q": "Which clue is most important for distinguishing the suspicious wireless network from the legitimate company network?",
                 "options": ["The suspicious network was detected near the parking area",
                             "The suspicious network had an unauthorized status and used the similar name NEONFORGE_FREE_WIFI instead of NEONFORGE_WIFI",
                             "The suspicious network remained visible until 07:02 PM",
                             "The suspicious network was connected to the Cybersecurity Lab"],
                 "answer": "B"},
                {"q": "Based on the initial case information, which element requires the most immediate forensic correlation rather than being treated as proof of a person's identity?",
                 "options": ["Rahul's presence near the parking area",
                             "Sanjay's administrator privileges",
                             "The unknown device with MAC 7A:31:9F:22:AC:10",
                             "The legitimate AP NF-AP-03"],
                 "answer": "C"},
            ]},
            "S2": {"name": "Gather the Evidence Set", "domain": "COLLECT", "mcqs": [
                {"q": "Investigators want to determine who created the rogue wireless profile. Which combination of evidence from the case file is most directly relevant?",
                 "options": ["Rahul's CCTV record, legitimate AP record, and server query log",
                             "Wireless controller log, wireless configuration audit, and Priya's workstation forensic image",
                             "Sanjay's switch session, Rahul's laptop MAC, and CCTV footage",
                             "Server authentication log, server query log, and legitimate network record"],
                 "answer": "B"},
                {"q": "Investigators need to determine whether the unknown device can be technically associated with a known workstation. Which evidence should they compare?",
                 "options": ["The unknown device's MAC/device fingerprint with the wireless adapter information in the workstation forensic image",
                             "Rahul's location on CCTV with the server's successful login time",
                             "Sanjay's administrator privileges with the legitimate AP location",
                             "The legitimate SSID with the duration of the CCTV recording"],
                 "answer": "A"},
                {"q": "Which evidence combination would best allow investigators to establish the relationship between the suspicious wireless activity and the later unauthorized server access?",
                 "options": ["Rogue AP scan + unknown device record + server authentication log",
                             "Rahul CCTV record + Sanjay administrator log + legitimate network record",
                             "Priya's CCTV movement + Rahul laptop history + legitimate AP record",
                             "Server query log + Sanjay switch session + Rahul's known networks"],
                 "answer": "A"},
            ]},
            "S3": {"name": "Correlate the Findings", "domain": "ANALYZE", "mcqs": [
                {"q": "Which sequence correctly reconstructs the major events using the timestamps in the case file?",
                 "options": ["Priya configuration -> failed login -> rogue AP -> unknown device -> successful login -> server query",
                             "Failed login -> Priya configuration -> rogue AP -> unknown device -> successful login -> server query",
                             "Failed login -> successful login -> Priya configuration -> rogue AP -> unknown device -> server query",
                             "Priya configuration -> rogue AP -> failed login -> successful login -> unknown device -> server query"],
                 "answer": "B"},
                {"q": "Which evidence provides the strongest correlation between Priya and the device involved in the rogue wireless activity?",
                 "options": ["Priya knew the legitimate wireless configuration and had access to lab equipment",
                             "Priya left the lab shortly before the rogue network appeared",
                             "The rogue device identifier 7A:31:9F:22:AC:10 is associated with the wireless adapter assigned to Priya's workstation, and the same rogue SSID profile is found in its forensic image",
                             "Priya's workstation was active shortly before 06:44 PM"],
                 "answer": "C"},
                {"q": "Which statement correctly distinguishes what the CCTV evidence establishes from what the laptop forensic evidence establishes about Rahul?",
                 "options": ["CCTV proves Rahul created the rogue AP, while the laptop record proves he connected to it",
                             "CCTV establishes Rahul's presence near the parking area, while the laptop evidence shows his recorded MAC differs from the rogue device and the rogue SSID was not found",
                             "CCTV establishes Rahul's device fingerprint, while the laptop evidence establishes Priya's wireless configuration activity",
                             "CCTV proves Rahul operated the unknown device, while the laptop record only shows that he previously used the legitimate network"],
                 "answer": "B"},
            ]},
            "S4": {"name": "Protect the Evidence", "domain": "PRESERVE", "mcqs": [
                {"q": "Which action is most consistent with the preservation requirements described in the case file?",
                 "options": ["Analyze the original evidence immediately and document the results afterward",
                             "Preserve original evidence, document timestamps and time zones, create forensic copies where appropriate, and maintain chain of custody",
                             "Delete unrelated logs before creating forensic copies",
                             "Reconfigure the rogue AP so investigators can reproduce the incident"],
                 "answer": "B"},
                {"q": "Which set of evidence should investigators prioritize for preservation because it contains time-sensitive records directly relevant to reconstructing the incident?",
                 "options": ["CCTV footage, wireless controller/configuration logs, and server authentication records",
                             "The legitimate SSID name, company description, and case title",
                             "Rahul's job role, Priya's role, and Sanjay's technical knowledge",
                             "The public company information and the authorized AP name"],
                 "answer": "A"},
                {"q": "Why should the original forensic evidence be preserved while investigators work from forensic copies where appropriate?",
                 "options": ["To ensure the evidence remains available for verification and that analysis does not alter the original material",
                             "To allow investigators to remove suspicious timestamps from the original",
                             "To ensure only the primary investigator can access the evidence",
                             "To replace the original evidence with a simplified investigation summary"],
                 "answer": "A"},
            ]},
            "S5": {"name": "Form the Conclusion", "domain": "REPORT", "mcqs": [
                {"q": "Which conclusion is best supported by the complete evidence chain in the case file?",
                 "options": ["Rahul is responsible because he was physically present near the parking area",
                             "Sanjay is responsible because he had administrator privileges",
                             "Priya is connected to the rogue Wi-Fi through the wireless configuration logs, workstation forensic evidence, and device-fingerprint correlation",
                             "The unknown device itself can be identified as the human attacker without further correlation"],
                 "answer": "C"},
                {"q": "Which evidence most directly eliminates Rahul as the operator of the rogue device?",
                 "options": ["Rahul was seen near the parking area at approximately 06:46 PM",
                             "Rahul's laptop was active during the incident window",
                             "Rahul's recorded Wi-Fi MAC A4:72:91:44:10:BC differs from the rogue device MAC, and the rogue SSID was not found on his laptop",
                             "Rahul's laptop had previously connected to NEONFORGE_WIFI"],
                 "answer": "C"},
                {"q": "Which statement should remain a limitation in the final report because it is not established by the supplied evidence?",
                 "options": ["Priya's workstation accessed the wireless configuration before the rogue AP appeared",
                             "The rogue device fingerprint was associated with Priya's workstation",
                             "The exact method by which the credentials used for the successful server authentication were obtained",
                             "The internal training server was queried after successful authentication"],
                 "answer": "C"},
            ]},
        },
    },
]


def blank_cases(n):
    """Return n throwaway case stubs (for `--stub` dev seeding)."""
    import copy
    out = []
    for i in range(n):
        c = copy.deepcopy(CASES[0])
        c["title"] = "STUB CASE %02d" % (i + 1)
        c["company"] = ""
        c["case_brief"] = "[STUB] placeholder narrative for dev smoke testing."
        c["objective"] = "[STUB] dev objective."
        out.append(c)
    return out